### ISSUE TITLE
Problem setting up development environment

### ISSUE THREAD

**Issue by tommazzo89** [ObeoNetwork/UML-Designer#1030]
Hi,

I'm working on a modeling topic for my computer science master thesis and would like to extend UML Designer. I'm having troubles setting up the development environment though:

I'm using a new installation of Eclipse Modeling Tools Photon with Sirius 6.0.1, Acceleo 3.7, and RCPTT IDE 2.3.0. I've cloned the UML Designer repository, opened the projects, merged the branch from [this pull request](https://github.com/ObeoNetwork/UML-Designer/pull/1022) to get Sirius 6.0 compatibility, and installed a few more dependencies. Yet I keep getting the following error in the org.obeonetwork.dsl.uml2.discovery project:
`Bundle 'org.eclipse.amalgam.discovery.ui' cannot be resolved`

I have the Amalgam Activity Explorer Developer Resources installed, but I cannot find anything that contains the org.eclipse.amalgam.discovery.ui bundle. I intentionally did not use the Oomph setup file, but I used it as a guide for the required components.

Can you please help me out?

Best regards,
Thomas

**Comment by mbats** [comment]
Hi,

Le 27/08/2018 à 19:20, Thomas Pusztai a écrit :
> I'm using a new installation of Eclipse Modeling Tools Photon with 
> Sirius 6.0.1, Acceleo 3.7, and RCPTT IDE 2.3.0. I've cloned the UML 
> Designer repository, opened the projects, merged the branch from this 
> pull request <https://github.com/ObeoNetwork/UML-Designer/pull/1022> to 
> get Sirius 6.0 compatibility, and installed a few more dependencies. Yet 
> I keep getting the following error in the 
> org.obeonetwork.dsl.uml2.discovery project:
> |Bundle 'org.eclipse.amalgam.discovery.ui' cannot be resolved|
> 
> I have the Amalgam Activity Explorer Developer Resources installed, but 
> I cannot find anything that contains the 
> org.eclipse.amalgam.discovery.ui bundle. I intentionally did not use the 
> Oomph setup file, but I used it as a guide for the required components.

Just close the org.obeonetwork.dsl.uml2.discovery plugin in your 
environment it is the only one requiring amalgam discovery : 
https://github.com/ObeoNetwork/UML-Designer/tree/master/plugins/org.obeonetwork.dsl.uml2.discovery
or you can try to install amalgam thanks to this update site : 
http://download.eclipse.org/modeling/amalgam/updates/stable/1.9.0-S20180326/capella

Best regards,
-- 
Mélanie Bats
CTO
+33 7 87 69 42 84
+33 5 34 57 16 29
@melaniebats

*Obeo*
25 Boulevard Victor Hugo - Colomiers - France
http://www.obeo.fr

**Comment by tommazzo89** [comment]
Perfect, thanks!
