### ISSUE TITLE
[UML-240] Suppr delete from model

### ISSUE THREAD

**Issue by cbrun** [ObeoNetwork/UML-Designer#153]
<b><i>[reporter="ldelaigue", created="Mon, 4 Mar 2013 15:22:45 +0100"]</i></b>
<p>Using the Suppr key on a diagram element remove the semantic element but as the diagrams are unsynchronized, it should just do a remove from diagram.</p>

**Comment by mbats** [comment]
Won't fix, we decided that the Suppr key must delete the semantic element but a pop up was implemented to prevent the deletion and ask user for confirmation.

Related to #667
