### ISSUE TITLE
[UML-211] Fix: Shared/Composite/Navigable AssociationEnds consistency (Class Diagram)

### ISSUE THREAD

**Issue by cbrun** [ObeoNetwork/UML-Designer#180]
<b><i>[reporter="cbrun", created="Fri, 1 Feb 2013 10:15:18 +0100", resolved="Fri, 1 Feb 2013 10:40:33 +0100"]</i></b>

<p>In the 2.0.0 version the usage of composition or aggregation tools is not consistent with the specification, and the display neither.</p>

<p>We should have for each association end</p>

<p>Navigable : Arrow<br/>
Composite : FillDiamond<br/>
Shared : Diamond</p>

<p>And compose these in the case of Navigable + Composite or Navigable+Aggregation</p>

<p>Furthermore, the "Composition" and "Aggregation" tools are setting the target member end as composite or shared, and should instead set the source member end.</p>

**Comment by Venator2013** [comment]
Shared/Composite/Navigable characteristic of a property is drawn on the wrong end of the edge for an association. 

It is written in the UML-Specification(2.5) at Page 200.

"When one end has aggregation = AggregationKind::shared a hollow diamond is added as a terminal adornment at the end of the Association line opposite the end marked with aggregation = AggregationKind::shared."

So according to the specification the style of an end correspond to the Aggregationkind of the opposite end.
