### ISSUE TITLE
Implement orthogonal regions

### ISSUE THREAD

**Issue by mbats** [ObeoNetwork/UML-Designer#376]
Today it is possible to create multiple regions but it is not possible to describe orthogonal regions.
See : http://en.wikipedia.org/wiki/UML_state_machine#Orthogonal_regions

**Comment by mPorhel** [comment]
"There is also a small problem with the rounded corner and the border."  

I will look to draw the rounded corner only for the first and last region bottoms of horizontal stacks and for the last region bottom for the vertical stack to avoid issue with the borders (ad future label line separator)

**Comment by mbats** [comment]
See Sirius bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=436359

**Comment by mPorhel** [comment]
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=470770 for the rounded corner issue. A patch set has been added to take the corner dimension to reduce the border line and draw the arcs of the corners. But for the moment, it only draw the arcs of the border attachment figure (Sirius display the left/top border of the compartment excepting the first one).

**Comment by mPorhel** [comment]
> The region border should be dashed.

See https://bugs.eclipse.org/bugs/show_bug.cgi?id=461590

**Comment by mbats** [comment]
Duplicate #397
