### ISSUE TITLE
[UML-378] Improve the layout of the splashscreen

### ISSUE THREAD

**Issue by cbrun** [ObeoNetwork/UML-Designer#44]
<b><i>[reporter="sbegaudeau", created="Mon, 21 Oct 2013 15:12:24 +0200"]</i></b>
<p>The current layout of the splashscreen is hiding part of the text and part of the progress bar. The progress bar could be made a bit smaller (in height) and the text could be placed a bit higher (5/10px higher max).</p>

<p>The issue is visible in the screenshot attached.</p>

**Comment by mbats** [comment]
Fixed.
