### ISSUE TITLE
Profile application :: editor :: displayed items :: tagged values not displayed in class diagram 

### ISSUE THREAD

**Issue by cboudjennah** [ObeoNetwork/UML-Designer#479]
Some users would like the tagged values of a stereotype within a profile to be displayed in the class diagram where a class having this stereotype is displayed.

**Comment by mbats** [comment]
We have to add a specific compartment to represent tagged values in class diagrams.
See http://www.uml-diagrams.org/profile-diagrams.html

And update the properties view consequently.

**Comment by cnotot** [comment]
Fixed.
Pushed for review: #579

**Comment by mbats** [comment]
We still have to represent the tagged values in the class diagram. We fixed only the properties view.
