### ISSUE TITLE
[UML-362] Move Up/Down only on container list elements

### ISSUE THREAD

**Issue by cbrun** [ObeoNetwork/UML-Designer#48]
<b><i>[reporter="mbats", created="Thu, 12 Sep 2013 10:57:46 +0200"]</i></b>
<p>In the package containment diagram, the pop up menu Move to > Up/Down should be visible only when an element is selected in a container list.<br/>
Today the beahviour is weird, as it is possible to select any component/package when you click on Move to > Up/Down, it will change the position of the currently selected element in its container.</p>

**Comment by mbats** [comment]
This issue exists also on class diagram to reorganise attributes/operations in a class.
