### ISSUE TITLE
[Sys2Soft][ergonomics]It should be to reveal in the model explorer an element in a diagram

### ISSUE THREAD

**Issue by cboudjennah** [ObeoNetwork/UML-Designer#523]
Initial conditions:
Tool started
A diagram is opened. This diagram must contain a few representations of model elements
The user clicks on an element displayed in the diagram
The user clicks on the "Link with Editor" button 

Problem:
The diagram node is revealed in the model explorer

Expected result:
The element whose representation was selected in the diagram should be revealed

**Comment by mbats** [comment]
See Sirius issue: https://bugs.eclipse.org/bugs/show_bug.cgi?id=460610

**Comment by mbats** [comment]
Fixed by Sirius 3.1.
