### ISSUE TITLE
Stereotype application objects should not be visible in the model explorer

### ISSUE THREAD

**Issue by fmadiot** [ObeoNetwork/UML-Designer#526]
Stereotype application objects should not be visible in the model explorer
![stereotypes](https://cloud.githubusercontent.com/assets/2065575/4419155/8332b994-4567-11e4-9189-8b032602cd4d.png)

**Comment by cnotot** [comment]
Fixed.
Pushed for review on master (Luna): #581

**Comment by mbats** [comment]
Integrated to master & juno3.8
