### ISSUE TITLE
Validation errors in uml.odesign

### ISSUE THREAD

**Issue by mbats** [ObeoNetwork/UML-Designer#541]
The validation of uml.odesign provides errors :
- on implicit variables : diagram, preSource...
  https://bugs.eclipse.org/bugs/show_bug.cgi?id=454003
- Invalid Type: viewpoint::DragAndDropTarget
  https://bugs.eclipse.org/bugs/show_bug.cgi?id=453056

These errors will be fixed in Sirius 2.0.2.
- on create view variable usage :
  https://bugs.eclipse.org/bugs/show_bug.cgi?id=454228

**Comment by mbats** [comment]
Check the order of the variable declaration in the select : 
aql:self.eContents()->select(EObject eObject | eObject.oclIsKindOf(uml::Class) or eObject.oclIsKindOf(uml::Component) or eObject.oclIsKindOf(uml::Package))
should be 
aql:self.eContents()->select(eObject EObject | eObject.oclIsKindOf(uml::Class) or eObject.oclIsKindOf(uml::Component) or eObject.oclIsKindOf(uml::Package))

**Comment by cbrun** [comment]
(in DE_Link) 

aql:self->including(Element elt|elt.getSource())->including(Element elt|elt.getTarget()) 

Can't possibly be correct as self is not a collection hence -> is not applicable on it.

should probably be 
aql:OrderedSet{self}->including( elt|elt.getSource())->including( elt|elt.getTarget())

**Comment by cbrun** [comment]
aql:i.target.nameExpression

in the OperationAction "Remove" need a cast or an instanceof  as the type can't be inferred.

**Comment by cbrun** [comment]
The mappings CD_Operation and CD_Property have a non valid semantic candidate expression has it gets applied on the abstract uml.Classifier which don't have the 'ownedOperation' and 'ownedAttribute' attributes.

You can either cast knowing it will fail at runtime for anything which is not an uml::Class or use the if:

aql:if self.oclIsKindOf(uml::Class) then self.ownedOperation else OrderdSet{} endif

**Comment by cbrun** [comment]
aql:views.target.defaultValue

in the OperationAction "Remove" need a cast or an instanceof as the type can't be inferred.

**Comment by cbrun** [comment]
in PackageHiearchy diagram

aql:edgeView.targetNode.target.eContainer()
and aql:edgeView.targetNode.target

in the Move operations contained in 'Reconnect package containment source'

are needing a cast, for instance:

aql:edgeView.targetNode.oclAsType(viewpoint::DSemanticDecorator).target

**Comment by cbrun** [comment]
in the use case diagram: (UCD_AddRelatedElements tool)

the expression aql:not diagram.containers->select(elt | elt.target=selection.subject) triggers a validation error as not (something returning a list) does not exist. 

Most likely the expression should be:

aql:not (diagram.containers->select(elt | elt.target=selection.subject)->size() > 0)

**Comment by cbrun** [comment]
The delete tool CS_Delete_Property seems linked to no mapping, making it unused at all in the .odesign
