### ISSUE TITLE
Existing comments are visible when creating new representation

### ISSUE THREAD

**Issue by men-devnat-grenoble** [ObeoNetwork/UML-Designer#551]
Reproduced with Obeo UML Designer version 4.0.1

When creating new representation of the model (class diagram), existing comments are displayed by default at the top of the new representation view.

Users have to hide them before to start working on the new representation.

**Comment by cnotot** [comment]
Fixed.
Pushed for review: https://github.com/ObeoNetwork/UML-Designer/pull/580

As now, the layer to display the comments is disabled by default.
So, when you create a new diagram, no comment is shown.
Besides, when you active this layer, only the "useful" comments are
displayed: the ones on the diagram itself and the ones attached to the
current visible graphical elements.

This fix applies on all the diagram kind representations.
