### ISSUE TITLE
Impossible to create an association class inside a package

### ISSUE THREAD

**Issue by men-devnat-grenoble** [ObeoNetwork/UML-Designer#554]
Using Obeo UML Designer version 4.0.1, it's impossible to create an association class inside a package.

Steps to reproduce:
- create a project and create a class diagram
- create a package foo
- create two class inside this package
- try to create an association class between these classes
- the association class will appear outside the package
- if you try to put it inside the package, the association class will be duplicated without links inside the package

**Comment by mbats** [comment]
Linked to https://github.com/ObeoNetwork/UML-Designer/issues/687
