### ISSUE TITLE
Support N-ary associations

### ISSUE THREAD

**Issue by mbats** [ObeoNetwork/UML-Designer#557]
In UML 2.5 spec see Section 11.5 Associations: 
* 11.5.3 Semantics: "For n-ary Associations, the lower multiplicity of an end is typically 0. A lower multiplicity for an end of an n-ary Association of 1 (or more) implies that one link (or more) must exist for every possible combination of values for the other ends."
* 11.5.4 Notations: "Any Association may be drawn as a diamond (larger than a terminator on a line) with a solid line for each Association memberEnd connecting the diamond to the Classifier that is the end’s type. An Association with more than two ends can only be drawn this way."
* 11.5.5 Examples: Figure 11.27 Binary and ternary Associations

See also: http://www.uml-diagrams.org/association.html

**Comment by fbats** [comment]
1. Specification : UML 2.5 spec see Section 11.5 Associations:
Chapter : 11.5.4 Notation
Any Association may be drawn as a diamond (larger than a terminator on a line) with a solid line for each Association
memberEnd connecting the diamond to the Classifier that is the end’s type. An Association with more than two ends can
only be drawn this way.

2. Modification

- Create a new mapping node represented by a diamond.

-  Create a new mapping edge from association end to previous mapping
These mapping are displayed if more than 3 ends are visibles in the diagram else the old mapping wil be displayed. 

- Rework creation tool
  If the user select association tool, he is able to modify existing  association to create a new end. 
  If the existing association is a binary association (shared or composite aggregation) tool could not be used.

- rework navigable arrow end. Navigable arrow end should be displayed as for previous mapping.

- rework owned change from property view

- add a validation to check if user change the Aggregation kind of an n-ary association
