### ISSUE TITLE
Cannot edit StereotypeApplication in EEF view when a stereotype is applied

### ISSUE THREAD

**Issue by cboudjennah** [ObeoNetwork/UML-Designer#560]
Version: UMLDesigner-5.0.0-juno3.8

Initial condition:
A model is opened and a profile is applied on the model.

Steps:
Apply a stereotype to a model element
Open the EEF propertiesn view

Problem:
StereotypeApplication cannot be edited. Only the stereotype can be. (this is problematic when the stereotype has attributes/tagged values)

Expected behaviour:
The EEF view should allow editing StereotypeApplication

**Comment by mbats** [comment]
Related to #479

**Comment by cnotot** [comment]
Fixed.
Pushed for review: #579
