### ISSUE TITLE
[Activity Diagrams]: Decision Nodes Behaving Like Merge Nodes

### ISSUE THREAD

**Issue by abiliooliveira** [ObeoNetwork/UML-Designer#574]
Apparently Decision Nodes are behaving the same as Merge Nodes, in the sense that no more than 1 outgoing edge is allowed.

**Comment by fthomasfr** [comment]
Yes, I have the same pb. I have checked the method isValidControlFlowStart but I don't understand yet why you cannot start a new control flow.

**Comment by fthomasfr** [comment]
That bug cannot be reproduced on the nightly build.

**Comment by mbats** [comment]
Fixed by a previous commit.
