### ISSUE TITLE
[Sys2Soft/4.2] 'Add' button on a class diagram has no effect

### ISSUE THREAD

**Issue by zmanzelji-tas** [ObeoNetwork/UML-Designer#578]

**Comment by cnotot** [comment]
Today, you can add UML Class, Interface, DataType, PrimitiveType, Enumeration, Package and AssociationClass elements on a Class Diagram.
When you click on this button, these kinds of UML element are proposed to be added.
Besides, you can add, on your diagram, elements which are located in other packages. For example, you have a model with directly 2 sub-packages 'p1' and 'p2', a Class 'A' in 'p1' and an Interface 'IA' in 'p2', and 'A' implements 'IA'. If you create a Class diagram on "p1", you can add 'A' and 'IA' to visualize the "implementation" link.

So, could you precise your request ?
Thanks.

**Comment by mbats** [comment]
Impossible to reproduce.

**Comment by mbats** [comment]
In fact the problem was that the Capture viewpoint must be activated as the Add tool is defined in the Capture viewpoint and reused in other viewpoints like the Design one.

**Comment by mbats** [comment]
Linked to #698
