### ISSUE TITLE
Literals type on enums should not be visible

### ISSUE THREAD

**Issue by juliendupont** [ObeoNetwork/UML-Designer#594]
Literals type on enum is present and should not be visible.

**Comment by electron378** [comment]
Julien, I would still treat it as a broader hide/show option, like: "..shall provide means to hide/show label elements of literals and attributes such as type and multiplicity (rationale: modeller needs means to control the duplication of visual information on a diagram; functionality present in major COTS tools)".
Thanks!

![literals](https://cloud.githubusercontent.com/assets/8280844/6872917/d9acd244-d4ac-11e4-8417-1093cbc0423a.png)

Regarding multiplicities - at least in our organisation it is a common practice to show it only when it is different from [1] so it would be helpful to have a hide/show control over multiplicity as well.
![multiplicity](https://cloud.githubusercontent.com/assets/8280844/6872921/defdbeac-d4ac-11e4-9b43-3c98e20be934.png)

**Comment by mbats** [comment]
Related to : #467
