### ISSUE TITLE
[UML-343] Revert UML Designer installation

### ISSUE THREAD

**Issue by cbrun** [ObeoNetwork/UML-Designer#61]
<b><i>[reporter="edugueperoux", created="Fri, 2 Aug 2013 15:13:01 +0200"]</i></b>
<p>I have tried to revert my UML Designer installation to 2.3.0 using the Installation History but an entry in the error log said the following :</p>

<p>No repository found containing: org.eclipse.update.feature,org.obeonetwork.dsl.feature.uml2,2.3.0.201306131556</p>

<p>it seems that old versions of UML Designer are not kept on update site. I you don't want to allows user to revert to old versions the feedback of the revert of p2 UI should be better than a error log entry.</p>

**Comment by mbats** [comment]
Won't fix.
