### ISSUE TITLE
Usecase diagram: tool tip coherence for palette tools

### ISSUE THREAD

**Issue by fbats** [ObeoNetwork/UML-Designer#652]
the palette tools have tooltips. Some time the tool tip is "Create ..." some time the tool tip is "Tool to create ..." and some time there is no tool tip such as Existing elements goup. 
Most of the time it is "create a new..." .

**Comment by mbats** [comment]
In fact, the tooltips must be reviewed for all the tools of all the diagrams as with the tool evolution some tooltips do not exist anymore.
