### ISSUE TITLE
Add constraints to attributes

### ISSUE THREAD

**Issue by MathieuAA** [ObeoNetwork/UML-Designer#731]
Hi,

Just dropping by to ask if it would be possible to add constraints to attributes (required, minlength, etc.).

**Comment by mbats** [comment]
It is not possible for the moment. We should implement it.

The purpose is to implement the UML Constraints. We should have a look to this document for the implementation: http://www.uml-diagrams.org/constraint.html

**Comment by MathieuAA** [comment]
Thanks for the quick reply.

**Comment by AxelRICHARD** [comment]
A first partial implementation for handling Constraints in class diagrams has been proposed https://github.com/ObeoNetwork/UML-Designer/pull/940

**Comment by MathieuAA** [comment]
Nice =)
