### ISSUE TITLE
Creating message with existing operation

### ISSUE THREAD

**Issue by mbats** [ObeoNetwork/UML-Designer#754]
In sequence diagram in UML Designer 5.0.0, it is not anymore possible to create a message which uses an exiting operation, the selection wizard is all the time empty.

**Comment by gmento** [comment]
Hi Mélanie

Can I have further information about the fixing of this bug?

Thanks

Giuseppe

**Comment by gerrytucker78** [comment]
I was also curious about the status of this fix.  Any ETA?

Thanks,
Gerry

**Comment by CCO68** [comment]
Hi,
is there any update on this bug?
In UML Designer 5.0 it is still not possible to select an existing operation in a sequence diagram.

Thanks
Cemal

**Comment by mbats** [comment]
This bug is fixed in UML Designer 7.0
