### ISSUE TITLE
Activity Diagram - Problem with body

### ISSUE THREAD

**Issue by men-devnat-grenoble** [ObeoNetwork/UML-Designer#757]
I don't know exactly when it happens but sometimes I can't delete the body of an opaque action.
I have created one opaque action and it was ok then I have created a second one and it was impossible to delete the body "// TODO..."

**Comment by ConquerorsHaki** [comment]
I have the same problem, only that I can't delete the body at all and if I enter some text I even get a second "// TODO body of OpaqueAction1"
Eclipse 4.5.2, UML Designer 6.0

**Comment by mbats** [comment]
Fixed by commit fb4cc5e
