### ISSUE TITLE
Erroneous management of brakets in direct editing of guards

### ISSUE THREAD

**Issue by mullertom** [ObeoNetwork/UML-Designer#785]
The algorithm managing the direct edition of guards is not correct. Here is how to reproduce an occurence of the bug : while editing a statemachine, the direct editing of guard labels manages square brackets (e.g. [ t1<2 & t4>3 ]).
If you insert a space after the last square bracket, the editor adds unwanted surrounding brackets (i.e. the displayed guard is then [[ t1<2 & t4>3 ] ]), and it is then possible to get unbalanced brackets.

**Comment by fbats** [comment]
j'ai traité le 786 en même temps.
