### ISSUE TITLE
non-Owned property of an association not created in the right element

### ISSUE THREAD

**Issue by jaracic** [ObeoNetwork/UML-Designer#789]
Example : 
![image](https://cloud.githubusercontent.com/assets/3204352/11975679/993ab746-a970-11e5-86ca-f93afca17a59.png)

In that case properties are owned by the association.

If I uncheck "Owned" int the "Member end" property list for the "class3s" property, I expected to see the property to appear in the class "class4"; It is not the case:
![image](https://cloud.githubusercontent.com/assets/3204352/11975734/2265b890-a971-11e5-940b-1035af5fa6dc.png)

**Comment by Venator2013** [comment]
I think this issue was fixed with commit 71986be4eea1444819100c6ef55da6c02a67b71c. Did you check out the nighty build?

**Comment by jaracic** [comment]
If I consider the code change, yes, it is fixed in the commit.
