### ISSUE TITLE
Convert Java file to UML Class

### ISSUE THREAD

**Issue by Testudinate** [ObeoNetwork/UML-Designer#790]
Hi.

Possible to convert Java file to UML Class directly ?

For example
![2](https://cloud.githubusercontent.com/assets/13544696/12000364/1e63d45e-aae6-11e5-864e-84362599d6e7.png)

Regards.

**Comment by Testudinate** [comment]
ping :-)

**Comment by mbats** [comment]
It is possible to do this thanks to the UML Generators project which can be found on the Eclipse website: https://www.eclipse.org/umlgen/

It is already possible to install easily the inverse feature UML to Java thanks to the Discovery feature in UML Designer: http://www.umldesigner.org/ref-doc/discovery.html

I will try to ease also the installation of the JAva to UML feature in future version.

**Comment by Testudinate** [comment]
Thanks for information, mbats !

**Comment by mbats** [comment]
Linked to #878

**Comment by Testudinate** [comment]
Thanks, mbats !  Super :-)

**Comment by AxelRICHARD** [comment]
UML to Java and Java to UML have been integrated to UML designer along with https://github.com/ObeoNetwork/UML-Designer/issues/921
