### ISSUE TITLE
Composition and Aggregation on the wrong end of new associations

### ISSUE THREAD

**Issue by ldelaigue** [ObeoNetwork/UML-Designer#811]
When I create a compisition or an aggregation, I expect the composite or aggregate "diamond" to be on the side of the first class I clicked. Currently, the diamond is on the opposite end.

**Comment by mbats** [comment]
Linked to #775

**Comment by mbats** [comment]
The creation tool must be reviewed, the users expect the inverse behavior. The diamond should be on the first selected end of the association.
