### ISSUE TITLE
No proposed viewpoint when you want to initialize a UML Diagram

### ISSUE THREAD

**Issue by cnotot** [ObeoNetwork/UML-Designer#818]
Do a right click on a UML model (where no aird exists for it) and click on "Initialize UML Diagram ...".
A window appears to define the location of the aird to be created.

Then, a new window appears to create a new representation but no representation type is proposed in this window.
You are obliged to click on "Cancel". Same thing if you do a right-click on the created aird and click on "Create representation".

In fact, no viewpoint is selected whereas this is a prerequisite to create some representations.
So, the wizard should insert a step between the aird location definition phase and the representation creation one in order to define the viewpoints to start to work with.

**Comment by fbats** [comment]
In the case you describe, the project might be a modeling project or not , Did you expect us to change the nature of the project to modeling?

**Comment by cnotot** [comment]
From a user point of view, the nature of the project has no sense for him. The user just wants to create a new set of representations (aird) on a project or a representation on a UML element. So, if this nature is required to be able to make that, so yes, you have to change this nature (I think).
