### ISSUE TITLE
Unique always shown for class diagramm

### ISSUE THREAD

**Issue by gerbsen** [ObeoNetwork/UML-Designer#820]
Hey there,
I just started with UML-Designer and found that the **unique** option is always active. It always shows `{unique}` in the diagram and the **unique** option is always selected if double clicked on the property. This happens to every property. The model.uml file does not contain "unique" and restarting UML-Designer did not change anything.
What am I doing wrong?
Cheers,
Daniel

**Comment by mbats** [comment]
Seems to have the same problem with the ordered option.

**Comment by mbats** [comment]
Related to #844
