### ISSUE TITLE
Is this project support python develop？

### ISSUE THREAD

**Issue by crazy-canux** [ObeoNetwork/UML-Designer#829]

**Comment by mbats** [comment]
UML Designer provides a graphical UML modeler to create uml model. You will obtain a uml2 model based on http://wiki.eclipse.org/MDT/UML2.
Then to generate code or reverse code you need to install/develop another component. For Java and C it exists the UML generators provided in Eclipse : https://www.eclipse.org/umlgen/
I do not know existing generators for python but you can develop your own.

**Comment by crazy-canux** [comment]
Understand.
thanks.
