### ISSUE TITLE
"Line Style: Tree Style Routing" shouldn't turn a corner when it only connects two classes in  Class Diagram

### ISSUE THREAD

**Issue by vegetable09** [ObeoNetwork/UML-Designer#831]

**Comment by AxelRICHARD** [comment]
Hello,

I'm not able to reproduce your problem. Can you give us a test case please ?

**Comment by mbats** [comment]
We have not enough information to reproduce, I close the issue, if you encounter the problem do not hesitate to reopen this issue by adding a case for reproduction.
