### ISSUE TITLE
Unable to reach the test page from the Developer guide menu

### ISSUE THREAD

**Issue by gcoutable** [ObeoNetwork/UML-Designer#832]
The [http://www.umldesigner.org/developer-guide/test.html](http://www.umldesigner.org/developer-guide/test.html) is not reachable from the **Developer guide** menu.

The *test* menu redirect to the *[Build](http://www.umldesigner.org/developer-guide/build.html)* page.

**Comment by mbats** [comment]
Integrated in master: https://github.com/ObeoNetwork/UML-Designer/pull/833
