### ISSUE TITLE
Ease the installation of Java to UML

### ISSUE THREAD

**Issue by mbats** [ObeoNetwork/UML-Designer#878]
Integrate the Java to UML generator from Eclipse UML Generators to the Discovery feature of UML Designer to simplify the installation of this component.

**Comment by AxelRICHARD** [comment]
The UML generators have been integrated to UML Designer along with https://github.com/ObeoNetwork/UML-Designer/issues/921

**Comment by amitmudata** [comment]
I am referring below link to generate my java source to UML then subsequently generate different UML diagrams……. http://www.umldesigner.org/ref-doc/umlgen.html
I should find option PFA as per link however cannot see the option, could you please suggest on the same.
Using below Obeo UMLDesigner version;
UML Designer 
Version  9.0.0
(c) Copyright (c) 2005-2018 Obeo. All Rights Reserved.
Few points noted are;
Apart from UMLDesigner do have eclipse neon 4.6, doc says Luna/Mars is require for UMLDesigner plugin has it anything to do with this..
![umlGenoption](https://user-images.githubusercontent.com/69377271/91523535-9c5d4080-e91a-11ea-9778-12b91ea3926a.png)
