### ISSUE TITLE
Missing HashSet import in JAVA classes generated from UML model

### ISSUE THREAD

**Issue by Johann-Angeli** [ObeoNetwork/UML-Designer#880]
I use UML2 to Java (version 3.0.0.) for generating my JAVA classes.

In case of fields representing a list of items, the generated code doesn't contains import for the targeted type (HashSet) and the code doesn't compile.

I'm oblige to manually add "import java.util.HashSet;"

**Environment**
- Eclipse NEON
- UMLGen Java Generator, version 3.0.0.201511201014
- UML Designer, version 7.0.0.201608031416
- JRE 1.8.0_45

**Comment by AxelRICHARD** [comment]
Hi,

I can't reproduce your problem with the UML Designer 7.1.0.

Can you provide us a test case to reproduce the problem please ?

**Comment by Johann-Angeli** [comment]
Hi,

I created a new workspace dedicated to this problem (see attached file).

The workspace contains : 

- a simple model with a class diagram including 2 classes.

- a java project regenerated by UML2 to JAVA

- the UML2 to JAVA configuration used for the Java code generation

[workspace-uml.zip](https://github.com/ObeoNetwork/UML-Designer/files/729307/workspace-uml.zip)
