### ISSUE TITLE
Generate JAVA classes with String fields initialized to null

### ISSUE THREAD

**Issue by Johann-Angeli** [ObeoNetwork/UML-Designer#881]
When generating JAVA classes from an UML model, I'm unable to generate String field initialized to null even if, in the model, the default value of the field is defined at "Literal Null".

![image](https://cloud.githubusercontent.com/assets/6648173/17519767/975c35b6-5e4d-11e6-8eef-41e2a98836a2.png)

The generated source :
    /**
     \* Description of the property uid.
     */
    private String uid = "";

**Environment**
- Eclipse NEON
- UMLGen Java Generator, version 3.0.0.201511201014
- UML Designer, version 7.0.0.201608031416
- JRE 1.8.0_45

**Comment by AxelRICHARD** [comment]
Hi,

The problem comes from the UMLGen project of Eclipse.
I raised a bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=510966, and proposed a patch to fix the problem.
