### ISSUE TITLE
Missing import in generated classes when using packages in a model

### ISSUE THREAD

**Issue by Johann-Angeli** [ObeoNetwork/UML-Designer#882]
When referencing classes, from an other package, in a model, the generated classes are missing the import related to that package.

In the following example, the vehicle class references an Engine from the package "powertrain".

![image](https://cloud.githubusercontent.com/assets/6648173/17520119/cab1e572-5e4e-11e6-8f67-9ff088515eae.png)

The generated source of the classe Vehicle
![image](https://cloud.githubusercontent.com/assets/6648173/17520142/df3aa9e8-5e4e-11e6-9362-598a57e5483d.png)

**Environment**
- Eclipse NEON
- UMLGen Java Generator, version 3.0.0.201511201014
- UML Designer, version 7.0.0.201608031416
- JRE 1.8.0_45

**Comment by AxelRICHARD** [comment]
Hi,

The problem comes from the UMLGen project of Eclipse.
I raised a bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=51980, and proposed a patch to fix the problem.

**Comment by Johann-Angeli** [comment]
Hi,

Thanks.

But it looks like the reported bug id is incorrect (bug id is 510980 and not 51980).
Then the good link is https://bugs.eclipse.org/bugs/show_bug.cgi?id=510980

**Comment by AxelRICHARD** [comment]
We finally migrated the UMLGen plug-ins into UML Designer.
The fix for this problem #882 has been integrated along with #921.
