### ISSUE TITLE
Image quality is very low

### ISSUE THREAD

**Issue by uname0708** [ObeoNetwork/UML-Designer#885]
Hi,
i have recently tried to work with UML Designer. I found it much useful than argoUML i have always use but it's very old.

However regarding exporting UML diagrams to images (PNG,JPG). The image produced is very low in quality and i didn't found any option to improve the quality.

Thanks.

**Comment by mbats** [comment]
Some work has been done in Sirius to improve the export:
* #491913  Improve export quality of gradient style for all format. See https://bugs.eclipse.org/bugs/show_bug.cgi?id=491913
* #498914 Exported SVGs don't show filled diamonds for containment references. See https://bugs.eclipse.org/bugs/show_bug.cgi?id=498914

As UML Designer 7.1.0 is based on Sirius 4.1 and so it should improve the export.

**Comment by mbats** [comment]
By the way, I also reported a resolution issue in Sirius in orde to improve this point in the future: https://bugs.eclipse.org/bugs/show_bug.cgi?id=507056
