### ISSUE TITLE
Root diagram container in state and activity diagrams complicates workflow

### ISSUE THREAD

**Issue by tjallingran** [ObeoNetwork/UML-Designer#897]
Activity diagrams and State diagrams have a root element that represents the Activity / State Machine.

This root element acts as a container in which all Actions / States, etc. must be located. This container is editable, in the sense that it can be moved across the diagram, resized, etc.. 

This 'editability' is often undesirable. It makes drag-select difficult. Drag-select is done by holding the left mouse button and then dragging a selection rectangle around the objects one wants to select. However, because the root element is editable, clicking the mouse left mouse button and moving the mouse, results in moving the root element around.

The workaround is drag-selecting from the background, but usually I work with a root element that is large enough to cover my entire screen, so I have to zoom out to do this. And even then, it forces the drag-selection to start at the edge of the root element.

Possible solutions:
- Change the root element (the Activity or State Machine) to be the diagram background (so that you can directly create activities on the background, instead of inside the container)
- Add an option to lock the root element, and interpret click+drag as a selection box

**Comment by AxelRICHARD** [comment]
Hi,

You can "drag-select" elements inside a container via the _Alt_ key. Is it suitable for you ?

Best regards

**Comment by tjallingran** [comment]
That sounds like a workable solution. Thanks for the tip. Could this info be added to the documentation? E.g. somewhere on http://www.umldesigner.org/ref-doc/define-the-application.html#Activity_Diagram ?

That said, it still seems a bit inconsistent to me that the root of these diagrams is different than, e.g. Class diagrams. Maybe that has to do with technicalities of the UML standard that I'm not aware of with?

**Comment by AxelRICHARD** [comment]
No this is a decision of ours, there are no technicalities reasons to do that.
Thanks for raising the problem and for your time !
