### ISSUE TITLE
User association in use-case diagram

### ISSUE THREAD

**Issue by AlbertEmbedded** [ObeoNetwork/UML-Designer#901]
UML 2.5 document, section 18.2.1.4 stands that : 

> associations
> An Actor can only have Associations to UseCases, Components, and Classes. Furthermore these Associations
> must be binary.
With the UML Designer  7.1.0 (  UML Designer 7.1.0.201611211359 )

- I succeed in creating an association between an actor and a UsesCase (OK)
- I can't succeed in creating an association between an actor and an Component
- I can't succeed in creating an association between an actor and a classe
- I succeed in creating an association between an actor and another actor

**Comment by AxelRICHARD** [comment]
A fix has been proposed https://github.com/ObeoNetwork/UML-Designer/pull/932
