### ISSUE TITLE
[UX] Sorting elements in model subtrees

### ISSUE THREAD

**Issue by AlbertEmbedded** [ObeoNetwork/UML-Designer#903]
(With the UML Designer 7.1.0 ( UML Designer 7.1.0.201611211359 ))
Presently (retro)building, prior a rework, a state machine with numerous states, it's sometimes hard to retrieve states already added.
It would be fine to be able to sort alphabetically subtrees in the tree of model explorer. Something like selecting a set of nodes, right click, context menu displays a "sort A..Z" entry and its sorts the set of selected nodes.

**Comment by AxelRICHARD** [comment]
Hello Albert,

This possible enhancement should be done in Sirius (the technology UML Designer is based on). So, I raised an enhancement bug in Sirius: https://bugs.eclipse.org/bugs/show_bug.cgi?id=512483

**Comment by AxelRICHARD** [comment]
Great news, after deeper investigation and discussion with the Sirius team, we decided to implement a "Sort Model Elements" action in the _Model Explorer View_ toolbar. When enabled, the model elements under semantic resources are sorted alphabetically.

Fix has been proposed https://github.com/ObeoNetwork/UML-Designer/pull/936

The documentation will be updated when the fix will be integrated to the repository.
