### ISSUE TITLE
[UX] Search elements in model

### ISSUE THREAD

**Issue by AlbertEmbedded** [ObeoNetwork/UML-Designer#904]
(With the UML Designer 7.1.0 ( UML Designer 7.1.0.201611211359 ))
Doing a search through the menu Search/Search should propose a search on the current model. Presently the only search availables are File, Java and Plugin. Files searchs implies saving the model before the search.

**Comment by AxelRICHARD** [comment]
Hello Albert,

You can search in your model from the search field of the Model Explorer View. You can also, in every diagram, use the shortcut Ctrl+O to open a search bar and starts to search elements in diagrams.
I also added a new section "Search" in the user documentation : https://github.com/ObeoNetwork/UML-Designer/pull/933

Best regards
