### ISSUE TITLE
[UX] Double click on a model element

### ISSUE THREAD

**Issue by AlbertEmbedded** [ObeoNetwork/UML-Designer#905]
(With the UML Designer 7.1.0 ( UML Designer 7.1.0.201611211359 ))
(Currently working with state machine diagrams and modele elements, but I presume its the same on other elements.)
When double-clicking on element in the mode-tree view explorer seems have no action. Same thing if double clicking a state on the diargam.
Coming from Entreprise Architect, I found it very convenient that double clicking an element displays its properties view

**Comment by AxelRICHARD** [comment]
Hello Albert,

If you opens the _Properties View_ by clicking on _Window > Show View > Other... > General Properties View_, then if you simple click on any model element from the _Model Explorer View_ or from any UML Diagram, the _Properties View_ will be updated wit the properties of the selected element.

Is it suitable for you ?

Best regards,
