### ISSUE TITLE
[Profile] Can't delete profile from Model Explorer Tree View

### ISSUE THREAD

**Issue by AlbertEmbedded** [ObeoNetwork/UML-Designer#906]
(With the UML Designer 7.1.0 ( UML Designer 7.1.0.201611211359 ))
* I create a new profile by right-clicking the <Model> Element => New representation => New profile diagram
* A new package with a profile is created
* Right click on the newly created package => Delete
* Nothing happens. Expected : profile to be deleted

Only bypass found : modifying the .uml file

**Comment by AxelRICHARD** [comment]
To reproduce the problem, once the profile diagram is created, user has to use the define profile tool from the palette. Then, the delete does not work. If the define profile tool is not applied, then the delete works.
