### ISSUE TITLE
Cannot create operations anymore

### ISSUE THREAD

**Issue by mbats** [ObeoNetwork/UML-Designer#907]
See the initial question on stackoverflow: http://stackoverflow.com/questions/40783035/methods-are-not-visible-in-class-diagram-umldesigner-7-1
"I had to switch my workspace and reimport my project into the new workspace. I am currently working on a class diagram. Everytime when i am creating a new method in a class it stays invisible. "

[UML_M.zip](https://github.com/ObeoNetwork/UML-Designer/files/613424/UML_M.zip)

**Comment by AxelRICHARD** [comment]
I found what is the "problem" here. The concerned diagram is not synchronized (right-click on the diagram background and click on the "unsynchronized" menu entry. If this option is disabled (that is the default state of Class diagram), then everything goes back to the "classic" behavior.
So there is no bug here.
