### ISSUE TITLE
Wrong title location for Device nodes in Deployment diagram

### ISSUE THREAD

**Issue by lredor** [ObeoNetwork/UML-Designer#908]
At creation, the title of a "Device" node is correctly located:
![newdevicenode](https://cloud.githubusercontent.com/assets/1825882/21264695/dd0dad96-c39d-11e6-835b-cd0fc258a062.jpg)
But if this node is increased vertically, the title is over the border of the node:
![devicenoderesized](https://cloud.githubusercontent.com/assets/1825882/21264701/e2e8d146-c39d-11e6-9456-c18fd5dcf1ef.jpg)

The problem is the same for "Node" and "Execution Environment" nodes (but not for the "Artifact").

This problem is probably caused by the 3D effect.

**Comment by AxelRICHARD** [comment]
Thank you Laurent for raising this problem. A fix has been proposed https://github.com/ObeoNetwork/UML-Designer/pull/939.
The problem came from the svg images used by the mappings.
I deleted the spaces around the shapes and everything is alright now.
