### ISSUE TITLE
missing modeling perspective in Eclipse Neon

### ISSUE THREAD

**Issue by gadic** [ObeoNetwork/UML-Designer#924]
When running Eclipse Neon.2 (4.6.2) with UML-Designer (7.1), I cannot find any Modeling perspective. Could this be a bug or an Eclipse configuration issue ?
The installation base is Eclipse Neon for C/C++ developers on Win7 64 bit.

**Comment by mbats** [comment]
I just tried your configuration, Eclipse Neon 2 with UML Designer 7.1 installed, and it works just fine. To switch to the `Modeling` Perspective, you can select `Open Perspective`
![selection_177](https://cloud.githubusercontent.com/assets/1185863/22459913/cf4b2322-e7a2-11e6-8065-2b85c80c35bd.png)
And then in the dialog selects the Modeling one.
![selection_178](https://cloud.githubusercontent.com/assets/1185863/22459934/e55e5b20-e7a2-11e6-9c86-36fbdee7ab9a.png)

**Comment by gadic** [comment]
Thanks for trying. Yes I guess it should work ;) but it does not for me.
![open_perspective](https://cloud.githubusercontent.com/assets/19164491/22460585/ccdd4b1c-e7a5-11e6-9775-c238764234ce.jpg)
The relevant installed software:
![installed_sw](https://cloud.githubusercontent.com/assets/19164491/22460644/1ba4a04c-e7a6-11e6-9be3-3d15c80b6cd4.jpg)

By the way, it is a fresh install of the Eclipse IDE Neon.2, and I realize that an error is reported:
java.lang.IllegalStateException: Registry Directory not available
Let's try to fix this first.

**Comment by gadic** [comment]
Although I couldn't point out what was wrong in my installation, doing this has fixed my issue. So it was related to Eclipse and not to UML Designer installation.
Thanks.
Can be closed.
