### ISSUE TITLE
using popup to add operations or change name of component does not save

### ISSUE THREAD

**Issue by thomas-covenant** [ObeoNetwork/UML-Designer#949]
case 1:
to a component diagram i add a component <component 2> 
double click it
change the name to securityManager
click finish
component has still the name <component 2>
changing in the model list at the left works
changing the name clicking on the diagram name wokrs

case 2:
double click the interface 
click operation tab
add operation "doLogin"
operation is added in the popup list as operation1
operation is not added in the model list 
add operation in the interface in the list adds it, and shows in the popup

eclipse neon.3
uml designer 7.1
linux ubuntu 16.10
eclipse is running in gtk 2 as there is a bug in eclipse with default

**Comment by mbats** [comment]
Fixed by commit https://github.com/ObeoNetwork/UML-Designer/commit/299b48a72e0a8705862e5155cb95ab35a2ecb45a
