### ISSUE TITLE
General tab is missing from the properties sheet

### ISSUE THREAD

**Issue by Alexandra93** [ObeoNetwork/UML-Designer#950]
Hello!
General tab is missing from the properties sheet of some nodes:  "Activity Partition", "Structured Activity Node" and "Expansion Region". 
Due to this fact, the double mouse click action, which supposed to open a pop-up properties window, is not working for this elements.

![bugreport](https://cloud.githubusercontent.com/assets/8112988/25995319/68590518-371a-11e7-93eb-5b7063aadfcf.PNG)

**Comment by mbats** [comment]
Thanks for your feedback, this should be fixed in the next release, as we reimplemented all the properties views. This bug is linked to #844.

**Comment by mbats** [comment]
Fixed by commit https://github.com/ObeoNetwork/UML-Designer/commit/299b48a72e0a8705862e5155cb95ab35a2ecb45a
