### ISSUE TITLE
Correct UML Designer guide

### ISSUE THREAD

**Issue by psuzzi** [ObeoNetwork/UML-Designer#951]
This is a minor issue about the help system.

In the help page "Creating your first UML Diagram", we read "In the wizard, expand 'UML Structural Modeling', select 'Class Diagram' and then 'Next'." But, to find "Class Diagram", we will need to expand the "Design" node.

![improve-uml-designer-guide-creating-first-uml-diagram](https://cloud.githubusercontent.com/assets/352831/26058974/5a02a524-3980-11e7-9b75-b9801b685e0d.png)

**Comment by mbats** [comment]
Thanks for your feedback, I will fix that!

**Comment by mbats** [comment]
Fixed by  8ef6866
