### ISSUE TITLE
Dialog pop-up is confusing

### ISSUE THREAD

**Issue by Alexandra93** [ObeoNetwork/UML-Designer#955]
Hello!
When moving the source of the 'include' relation from one Use Case to another, according to the pop-up, there will be 2 deletes - but the second one does not exists. This behaviour can be confusing. 

![image](https://cloud.githubusercontent.com/assets/8112988/26190143/9855c68a-3bb0-11e7-8146-0c452b1b04fe.png)

A move is an add and a delete in the semantic model and it would be nice to be able to show the difference (suggestion: add = green, delete = red, update = yellow).

**Comment by mbats** [comment]
Linked to #960
