### ISSUE TITLE
help page: import primitives

### ISSUE THREAD

**Issue by thomas-covenant** [ObeoNetwork/UML-Designer#958]
on the help page it states the following:
"The contextual menu Import primitive types can import predefined types libraries from a right-click on the background of a class diagram. This menu allows to import primitives for :"

This is wrong. you have to right-click on a class to get the contextual menu with the import

**Comment by mbats** [comment]
You can right click either on the background or on the class. On the following screenshot I right clicked on the diagram background.
![selection_075](https://user-images.githubusercontent.com/1185863/27337446-b8be78a4-55d2-11e7-865e-d80bc1d63da2.png)

**Comment by mbats** [comment]
Nothing to fix.
