### ISSUE TITLE
Visibility is not set at the first creation

### ISSUE THREAD

**Issue by GeoffreyGamaya** [ObeoNetwork/UML-Designer#961]
When a new Class or Attribute or Operation is created even if the Visibility is set on public the green cross is not visible on the diagram.

We need to re-open the dialog box, set the Visibility to private and re-change it to public.

**Comment by mbats** [comment]
Fixed by commit https://github.com/ObeoNetwork/UML-Designer/commit/44538e5424f2e171e2623465cf250a1cba1bf8c2
